services:
  minio1:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    # container_name: minio1
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
      - MINIO_DISTRIBUTED_MODE_ENABLED=no

      - MINIO_SCHEME=http
      # - MINIO_DISTRIBUTED_NODES=minio1,minio2,minio3,minio4
      #- MINIO_SKIP_CLIENT=yes
    # volumes:
    #   - minio1-data:/bitnami/minio/data
    ports:
      - "9002:9000"
      - "9001:9001"  # Console UI
      
    # command: server --address ":9000" --console-address ":9001" http://minio{1...4}/bitnami/minio/data
    command: server --address ":9000" --console-address ":9001" /bitnami/minio/data
    cpus: "2.0"
    networks:
      - ecommerce_network

  minio-init:
    image: minio/mc
    depends_on:
      - minio1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local http://minio1:9000 admin admin123) do echo 'Waiting for MinIO...' && sleep 1; done;
      /usr/bin/mc mb --ignore-existing local/datalake;
      /usr/bin/mc policy set public local/datalake;
      exit 0;
      "
    networks:
      - ecommerce_network