services:
  iceberg-rest:
    image: apache/iceberg-rest-fixture
    container_name: iceberg-rest
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin123
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://datalake/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio1:9000
      # - CATALOG_S3_ACCESS_KEY_ID=admin
      # - CATALOG_S3_SECRET_ACCESS_KEY=admin123
      # - CATALOG_S3_PATH_STYLE_ACCESS=true
    networks:
      - ecommerce_network